### ISSUE TITLE
Interaktive Beispielbilder

### ISSUE THREAD

**Issue by epoyraz** [zeka-hazinesi/nextjs-frontend#8]
#### Zusammenfassung
Aktuell bietet die Seite "Bildgenerator" nur statische Beispielbilder, um die Funktionen des Generators zu demonstrieren. Interaktive Beispielbilder könnten die Benutzererfahrung erheblich verbessern und potenzielle Anwendungsfälle besser veranschaulichen.

#### Schritte zur Reproduktion (falls zutreffend)
1. Navigieren Sie zur Seite "Bildgenerator".
2. Beachten Sie die vorhandenen statischen Beispielbilder.

#### Erwartetes Verhalten
Interaktive Beispielbilder sollten vorhanden sein, die dem Benutzer ermöglichen, die Funktionalität des Generators besser zu verstehen. Diese Bilder könnten anklickbar sein, um weitere Informationen oder Live-Demos zu bieten.

#### Aktuelles Verhalten
Es gibt derzeit nur statische Beispielbilder, die wenig über die Möglichkeiten des Generators aussagen.

#### Mögliche Lösung
Implementieren Sie interaktive Beispielbilder, die bei Klick erweiterte Informationen oder Live-Demos bieten. Diese könnten Tooltips, Pop-ups oder Modal-Fenster mit weiteren Details enthalten.

**Comment by sinopino391** [comment]
Interaktive Beispielbilder eingefügt, beim Klick auf ein Beispielbild wird es in das Drop Feld angezeigt und kann genutzt werden

hochgeladen im Branch "localbranch"

**Comment by epoyraz** [comment]
@sinopino391  mach ein PR
